package ucuenca.registrocapacitaciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dtic_rec_evaluacion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "EVALUACION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "EVALUACION_ID_SEQ", name = "EVALUACION_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Integer preg_1_1;

   private java.lang.Integer preg_1_2;

   private java.lang.Integer preg_1_3;

   private java.lang.Integer preg_1_4;

   private java.lang.Integer preg_1_5;

   private java.lang.String preg_2;

   private java.lang.String preg_3;

   private java.lang.String preg_4;

   private java.lang.String preg_5;

   private java.lang.Long eventoID;

   private org.jbpm.document.Document certificadoEvento;

   private java.lang.Long participanteID;

   public dtic_rec_evaluacion()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getPreg_1_1()
   {
      return this.preg_1_1;
   }

   public void setPreg_1_1(java.lang.Integer preg_1_1)
   {
      this.preg_1_1 = preg_1_1;
   }

   public java.lang.Integer getPreg_1_2()
   {
      return this.preg_1_2;
   }

   public void setPreg_1_2(java.lang.Integer preg_1_2)
   {
      this.preg_1_2 = preg_1_2;
   }

   public java.lang.Integer getPreg_1_3()
   {
      return this.preg_1_3;
   }

   public void setPreg_1_3(java.lang.Integer preg_1_3)
   {
      this.preg_1_3 = preg_1_3;
   }

   public java.lang.Integer getPreg_1_4()
   {
      return this.preg_1_4;
   }

   public void setPreg_1_4(java.lang.Integer preg_1_4)
   {
      this.preg_1_4 = preg_1_4;
   }

   public java.lang.Integer getPreg_1_5()
   {
      return this.preg_1_5;
   }

   public void setPreg_1_5(java.lang.Integer preg_1_5)
   {
      this.preg_1_5 = preg_1_5;
   }

   public java.lang.String getPreg_2()
   {
      return this.preg_2;
   }

   public void setPreg_2(java.lang.String preg_2)
   {
      this.preg_2 = preg_2;
   }

   public java.lang.String getPreg_3()
   {
      return this.preg_3;
   }

   public void setPreg_3(java.lang.String preg_3)
   {
      this.preg_3 = preg_3;
   }

   public java.lang.String getPreg_4()
   {
      return this.preg_4;
   }

   public void setPreg_4(java.lang.String preg_4)
   {
      this.preg_4 = preg_4;
   }

   public java.lang.String getPreg_5()
   {
      return this.preg_5;
   }

   public void setPreg_5(java.lang.String preg_5)
   {
      this.preg_5 = preg_5;
   }

   public java.lang.Long getEventoID()
   {
      return this.eventoID;
   }

   public void setEventoID(java.lang.Long eventoID)
   {
      this.eventoID = eventoID;
   }

   public org.jbpm.document.Document getCertificadoEvento()
   {
      return this.certificadoEvento;
   }

   public void setCertificadoEvento(org.jbpm.document.Document certificadoEvento)
   {
      this.certificadoEvento = certificadoEvento;
   }

   public java.lang.Long getParticipanteID()
   {
      return this.participanteID;
   }

   public void setParticipanteID(java.lang.Long participanteID)
   {
      this.participanteID = participanteID;
   }

   public dtic_rec_evaluacion(java.lang.Long id, java.lang.Integer preg_1_1,
         java.lang.Integer preg_1_2, java.lang.Integer preg_1_3,
         java.lang.Integer preg_1_4, java.lang.Integer preg_1_5,
         java.lang.String preg_2, java.lang.String preg_3,
         java.lang.String preg_4, java.lang.String preg_5,
         java.lang.Long eventoID, org.jbpm.document.Document certificadoEvento,
         java.lang.Long participanteID)
   {
      this.id = id;
      this.preg_1_1 = preg_1_1;
      this.preg_1_2 = preg_1_2;
      this.preg_1_3 = preg_1_3;
      this.preg_1_4 = preg_1_4;
      this.preg_1_5 = preg_1_5;
      this.preg_2 = preg_2;
      this.preg_3 = preg_3;
      this.preg_4 = preg_4;
      this.preg_5 = preg_5;
      this.eventoID = eventoID;
      this.certificadoEvento = certificadoEvento;
      this.participanteID = participanteID;
   }

}