package ucuenca.registrocapacitaciones;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.ParseException; 

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dtic_rec_informe implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "INFORME_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "INFORME_ID_SEQ", name = "INFORME_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String cargo;

   private java.lang.String dependencia;

   private java.util.Date fecha;

   private org.jbpm.document.Document informeEvento;

   private java.lang.String responsable;

   private java.lang.Long eventoID;
   
   @javax.persistence.Transient
   SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
   

   public dtic_rec_informe()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.String getDependencia()
   {
      return this.dependencia;
   }

   public void setDependencia(java.lang.String dependencia)
   {
      this.dependencia = dependencia;
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = corregirFecha(fecha);
   }

   public org.jbpm.document.Document getInformeEvento()
   {
      return this.informeEvento;
   }

   public void setInformeEvento(org.jbpm.document.Document informeEvento)
   {
      this.informeEvento = informeEvento;
   }

   public java.lang.String getResponsable()
   {
      return this.responsable;
   }

   public void setResponsable(java.lang.String responsable)
   {
      this.responsable = responsable;
   }

   public java.lang.Long getEventoID()
   {
      return this.eventoID;
   }

   public void setEventoID(java.lang.Long eventoID)
   {
      this.eventoID = eventoID;
   }

public Date corregirFecha(Date fecha_tmp)
   {
      if (fecha_tmp != null)
      {
         int anio = Integer.parseInt(formatoFecha.format(fecha_tmp).substring(6));
         if (anio < 999)
         {
            anio += 2000;
            try
            {
               fecha_tmp = formatoFecha.parse(formatoFecha.format(fecha_tmp).substring(0, 6) + anio);
            }
            catch (ParseException ex)
            {
               System.out.println("error parse: fecha_tmp");
            }
         }
      }
      return fecha_tmp;
   }

   public dtic_rec_informe(java.lang.Long id, java.lang.String cargo,
         java.lang.String dependencia, java.util.Date fecha,
         org.jbpm.document.Document informeEvento, java.lang.String responsable,
         java.lang.Long eventoID)
   {
      this.id = id;
      this.cargo = cargo;
      this.dependencia = dependencia;
      this.fecha = fecha;
      this.informeEvento = informeEvento;
      this.responsable = responsable;
      this.eventoID = eventoID;
   }

}