package ucuenca.registrocapacitaciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dtic_rec_participante implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PARTICIPANTE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PARTICIPANTE_ID_SEQ", name = "PARTICIPANTE_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String nombre;

   private java.lang.String dependencia;

   private java.lang.String cargo;

   @org.kie.api.definition.type.Label("Correo Institucional")
   private java.lang.String correo;

   @org.kie.api.definition.type.Label("¿Requiere Viáticos?")
   private java.lang.String viaticos;

   @org.kie.api.definition.type.Label("Estado Evento")
   private java.lang.String estado_evento;

   @org.kie.api.definition.type.Label("cedula")
   private java.lang.String cedula;

   public dtic_rec_participante()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getDependencia()
   {
      return this.dependencia;
   }

   public void setDependencia(java.lang.String dependencia)
   {
      this.dependencia = dependencia;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.String getCorreo()
   {

      return this.correo;
   }

   public void setCorreo(java.lang.String correo)
   {
      this.correo = correo;
   }

   public java.lang.String getViaticos()
   {
      return this.viaticos;
   }

   public void setViaticos(java.lang.String viaticos)
   {
      this.viaticos = viaticos;
   }

   public java.lang.String getEstado_evento()
   {
      return this.estado_evento;
   }

   public void setEstado_evento(java.lang.String estado_evento)
   {
      this.estado_evento = estado_evento;
   }

   public java.lang.String getUID()
   {
      String email;
      email = this.correo;
      int index = email.indexOf("@");
      email = email.substring(0, index);
      return email;
   }

   public java.lang.String getCedula()
   {
      return this.cedula;
   }

   public void setCedula(java.lang.String cedula)
   {
      this.cedula = cedula;
   }

   public dtic_rec_participante(java.lang.Long id, java.lang.String nombre,
         java.lang.String dependencia, java.lang.String cargo,
         java.lang.String correo, java.lang.String viaticos,
         java.lang.String estado_evento, java.lang.String cedula)
   {
      this.id = id;
      this.nombre = nombre;
      this.dependencia = dependencia;
      this.cargo = cargo;
      this.correo = correo;
      this.viaticos = viaticos;
      this.estado_evento = estado_evento;
      this.cedula = cedula;
   }

}